#ifndef LIGHTNVR_VERSION_H
#define LIGHTNVR_VERSION_H

#define LIGHTNVR_VERSION_MAJOR 
#define LIGHTNVR_VERSION_MINOR 
#define LIGHTNVR_VERSION_PATCH 
#define LIGHTNVR_VERSION_STRING ""

#define LIGHTNVR_BUILD_DATE ""
#define LIGHTNVR_GIT_COMMIT ""

#endif // LIGHTNVR_VERSION_H
