# Stage 1: Build image
FROM alpine:latest AS builder

RUN apk update && apk add --no-cache \
    git cmake build-base pkgconfig \
    ffmpeg-dev sqlite-dev \
    curl-dev \
    mbedtls2-dev \
    cjson-dev \
    mosquitto-dev \
    bash

# Fetch external dependencies
RUN mkdir -p /opt/external && \
    # ezxml
    cd /opt/external && \
    git clone https://github.com/lxfontes/ezxml.git && \
    # inih
    cd /opt/external && \
    git clone https://github.com/benhoyt/inih.git

# Copy current directory contents into container
WORKDIR /opt
COPY . .

# Clean any existing build files and build the application
RUN mkdir -p /etc/oneberry /var/lib/oneberry/data /var/log/oneberry /var/run/oneberry && \
    chmod -R 777 /var/lib/oneberry /var/log/oneberry /var/run/oneberry && \
    # Clean any existing build files
    rm -rf build/ && \
    # Build the application
    # PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH \
    ./scripts/build.sh --release --with-sod && \
    ./scripts/install.sh --prefix=/ --without-systemd --without-ldconfig

# Stage 2: Minimal runtime image
FROM alpine:latest AS final

# Install runtime dependencies
RUN apk update && apk add --no-cache \
    ffmpeg-libavformat \
    sqlite-libs \
    ffmpeg-libavcodec \
    ffmpeg-libswscale \
    libcurl \
    mbedtls2 \
    cjson \
    mosquitto-libs

# Create necessary directories in runtime
RUN mkdir -p /etc/oneberry /var/lib/oneberry/data /var/log/oneberry /var/run/oneberry && \
    chmod -R 777 /var/lib/oneberry /var/log/oneberry /var/run/oneberry

# Copy compiled binary and config files from builder stage
COPY --from=builder /bin/oneberry /bin/oneberry
COPY --from=builder /etc/oneberry /etc/oneberry
COPY --from=builder /var/lib/oneberry /var/lib/oneberry
COPY --from=builder /var/log/oneberry /var/log/oneberry
COPY --from=builder /var/run/oneberry /var/run/oneberry
COPY --from=builder /lib/libsod.so.1.1.9 /lib/libsod.so.1.1.9
COPY --from=builder /lib/libsod.so.1.1.9 /lib/libsod.so.1
COPY --from=builder /lib/libsod.so.1 /lib/libsod.so

# Expose required ports
EXPOSE 8080

# Volume for configuration and data persistence
# /etc/oneberry - Configuration files
# /var/lib/oneberry/data - Persistent data (database, recordings, models, etc.)
VOLUME /etc/oneberry
VOLUME /var/lib/oneberry/data

# Command to start the service
CMD ["/bin/oneberry", "-c", "/etc/oneberry/oneberry.ini"]
